/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "imgproc.h"

bool_t
xdr_image (XDR *xdrs, image *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->channels))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->width);
		IXDR_PUT_LONG(buf, objp->height);
		IXDR_PUT_LONG(buf, objp->channels);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, 5000000))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->width))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->height))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->channels))
				 return FALSE;

		} else {
		objp->width = IXDR_GET_LONG(buf);
		objp->height = IXDR_GET_LONG(buf);
		objp->channels = IXDR_GET_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, 5000000))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->width))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->height))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->channels))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, 5000000))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_result (XDR *xdrs, result *objp)
{
	register int32_t *buf;

	 if (!xdr_image (xdrs, &objp->img_seq))
		 return FALSE;
	 if (!xdr_image (xdrs, &objp->img_par))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->time_seq))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->time_par))
		 return FALSE;
	return TRUE;
}
