/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IMGPROC_H_RPCGEN
#define _IMGPROC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct image {
	int width;
	int height;
	int channels;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct image image;

struct result {
	image img_seq;
	image img_par;
	double time_seq;
	double time_par;
};
typedef struct result result;

#define IMG_PROG 0x20000002
#define IMG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define procesar 1
extern  result * procesar_1(image *, CLIENT *);
extern  result * procesar_1_svc(image *, struct svc_req *);
extern int img_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define procesar 1
extern  result * procesar_1();
extern  result * procesar_1_svc();
extern int img_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_image (XDR *, image*);
extern  bool_t xdr_result (XDR *, result*);

#else /* K&R C */
extern bool_t xdr_image ();
extern bool_t xdr_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IMGPROC_H_RPCGEN */
